//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drnosv6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public string ID { get; set; }
        public string Degree1 { get; set; }
        public string Description { get; set; }
        public int DegID { get; set; }
    }
}
