//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drnosv6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int RVH_ID_ { get; set; }
        public string NPI { get; set; }
        public bool On_Staff { get; set; }
        public bool AdmPriv { get; set; }
        public bool Inactive { get; set; }
        public string License_Verification_Date { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Group { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string State { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Phys_Spclty { get; set; }
        public string License_ { get; set; }
        public string UPIN { get; set; }
        public bool QCPR { get; set; }
        public bool Keane { get; set; }
        public bool Orsos { get; set; }
        public bool C3M { get; set; }
        public bool Soft { get; set; }
        public bool DIC { get; set; }
        public bool Metalink { get; set; }
        public bool Open_Med { get; set; }
        public bool Muse { get; set; }
        public bool MedQuest { get; set; }
        public string Degree1 { get; set; }
        public string Degree2 { get; set; }
        public string Degree3 { get; set; }
    }
}
