//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drnosv6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty
    {
        public string SpecialtyID { get; set; }
        public string SpecialtyAlias { get; set; }
        public string DescriptiveText { get; set; }
    }
}
